const express = require('express');

const router = express.Router();
const { getRoles } = require('../controllers/rolController.js');

/**
 * @swagger
 *   components:
 *     schemas:
 *       Rol:
 *         type: object
 *         properties:
 *           id:
 *             type: integer
 *             description: Autogenerated id.
 *           rol:
 *             type: string
 *             description: String value.
 *             enum: [ADMIN, USER]
 *           descripcion:
 *             type: string
 *             description: Observations, comments or remarks.
 *           activo:
 *             type: string
 *             description: Is rol active?
 *           createAt:
 *             type: string
 *             format: date-time
 *             description: Timestamp of creation in 'Z time'
 *             readOnly: true
 *           updatedAt:
 *             type: string
 *             format: date-time
 *             description: Timestamp of latest update in 'Z time'
 *             readOnly: true
 */

/**
 * @swagger
 *   /roles:
 *     get:
 *       summary: List of roles.
 *       description: Retrieves list with rol objects.
 *       tags: [Roles]
 *       responses:
 *         200:
 *           description: A list of roles.
 *           content:
 *             application/json:
 *               schema:
 *                 type: object
 *                 properties:
 *                   data:
 *                     type: array
 *                     items:
 *                       $ref: '#/components/schemas/Rol'
 *         429:
 *           $ref: '#/components/responses/TooManyRequests'
 *         500:
 *           $ref: '#/components/responses/InternalServerError'
 */
router.get('/', getRoles);

module.exports = router;