# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  
    steps:
    - name: Create dot env file
      run: |
            touch .env
            echo POSTGRE_TEST_USER=${{secrets.POSTGRE_TEST_USER}} >> .env
            echo POSTGRE_TEST_PASS=${{secrets.POSTGRE_TEST_PASS}} >> .env
            echo POSTGRE_TEST_DB_NAME=${{secrets.POSTGRE_TEST_DB_NAME}} >> .env
            echo POSTGRE_TEST_HOST=${{secrets.POSTGRE_TEST_HOST}} >> .env
            echo POSTGRE_TEST_PORT=${{secrets.POSTGRE_TEST_PORT}} >> .env
            cat .env
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
